name: Build

on:
  push

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Build
        run: |
          xcodebuild clean \
          -workspace cafelogos-pos.xcworkspace \
          -scheme cafelogos-pos \
          -configuration debug

      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
          -workspace cafelogos-pos.xcworkspace \
          -scheme cafelogos-pos \
          -configuration debug

      - name: Archive Project
        run: |
          xcodebuild \
          -workspace cafelogos-pos.xcworkspace \
          -scheme cafelogos-pos \
          -sdk iphoneos \
          -configuration debug \
          -derivedDataPath build \
          -archivePath build/archive.xcarchive \
          CODE_SIGNING_ALLOWED=NO
