name: iOS Build CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.3app

      - name: Resolve Swift packages
        run: xcodebuild -resolvePackageDependencies \
          -workspace cafelogos-pos.xcworkspace \
          -scheme "[Debug] cafelogos-pos"

      - name: Build (Debug for simulator)
        run: |
          xcodebuild \
            -workspace cafelogos-pos.xcworkspace \
            -scheme "[Debug] cafelogos-pos" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPad Pro (11-inch) (4th generation)' \
            -configuration Debug \
            build \
            | xcpretty
