name: iOS Build CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Select Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Copy Signing.xcconfig
        run: cp Signing.xcconfig.example Signing.xcconfig

      - name: Resolve Swift packages
        run: xcodebuild -resolvePackageDependencies
          -workspace cafelogos-pos.xcworkspace 
          -scheme "cafelogos-pos"

      - name: Build without Code Signing
        run: |
          xcodebuild \
            -workspace cafelogos-pos.xcworkspace \
            -scheme cafelogos-pos \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPad Pro 11-inch (M4)' \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_PREVIEWS=NO \
            ENABLE_SWIFT_MACROS=YES \
            build

