name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint
    
    - name: Build and Test LogoREGICore
      run: |
        cd LogoREGICore
        swift build
        swift test
    
    - name: Build Debug Configuration
      run: xcodebuild -workspace cafelogos-pos.xcworkspace -scheme cafelogos-pos -configuration Debug build CODE_SIGNING_ALLOWED=NO
    
    - name: Build Release Configuration
      run: xcodebuild -workspace cafelogos-pos.xcworkspace -scheme cafelogos-pos -configuration Release build CODE_SIGNING_ALLOWED=NO
